export class knowledge {
      levelOfKnowledgeIonic: number;
      levelOfKnowledgeAndroid: number;
      levelOfKnowledgeIOS: number;
      levelOfKnowledgeHTML: number;
      levelOfKnowledgeCSS: number;
      levelOfKnowledgeBootstrap: number;
      levelOfKnowledgeJquery: number;
      levelOfKnowledgeAngularJs: number;
      levelOfKnowledgeJava: number;
      levelOfKnowledgeAspNetMVC: number;
      levelOfKnowledgeC: number;
      levelOfKnowledgeCPlusPlus: number;
      levelOfKnowledgeCake: number;
      levelOfKnowledgeDjango: number;
      levelOfKnowledgeMajento: number;
      levelOfKnowledgePHP: number;
      levelOfKnowledgeWordpress: number;
      levelOfKnowledgePhyton: number;
      levelOfKnowledgeRuby: number;
      levelOfKnowledgeMySQLServer: number;
      levelOfKnowledgeMySQL: number;
      levelOfKnowledgeSalesforce: number;
      levelOfKnowledgePhotoshop: number;
      levelOfKnowledgeIllustrator: number;
      levelOfKnowledgeSEO: number;
      otherLanguageOrFramework: string;
      linkCRUD: string
}